GTDB/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'GTDB.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	
	url(r'^', include('getregi.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

getregi/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('getregi.views',
	url(r'^gtdb/$', 'index'),
	url(r'^search/$', 'index_search'),
	url(r'^browse/$', 'index_browse'),
	url(r'^laboratories/$', 'index_laboratory'),
	url(r'^diseases/$', 'index_disease'),
	url(r'^genes/$', 'index_gene'),
#	url(r'^genepanels/$', 'index_genepanel'),
	url(r'^genetictests/$', 'index_genetictest'),
	url(r'^rizivcodes/$', 'index_rizivcode'),
	url(r'^personnel/$', 'index_personnel'),
	url(r'^methodology/$', 'index_methodology'),
	url(r'^laboratories/(?P<laboratory_id>\d+)/$', 'detail_laboratory'),
	url(r'^diseases/(?P<disease_id>\d+)/$', 'detail_disease'),
	url(r'^genes/(?P<gene_id>\d+)/$', 'detail_gene'),
	url(r'^genepanels/(?P<genepanel_id>\d+)/$', 'detail_genepanel'),
	url(r'^genetictests/(?P<genetictest_id>\d+)/$', 'detail_genetictest'),
	url(r'^personnel/(?P<personnel_id>\d+)/$', 'detail_personnel'),
	url(r'^methodcategories/(?P<methodcategory_id>\d+)/$', 'detail_methodcategory'),
	url(r'^methodtechniques/(?P<methodtechnique_id>\d+)/$', 'detail_methodtechnique'),
	url(r'^methodplatforms/(?P<methodplatform_id>\d+)/$', 'detail_methodplatform'),
)

getregi/models.py
from django.db import models
import datetime

# Create your models here.

class Laboratory(models.Model):
	CITY_CHOICES = (
		('Antwerpen', 'Antwerpen'),
		('Brussel', 'Brussel'),
		('Gent', 'Gent'),
		('Gosselies', 'Gosselies'),
		('Leuven', 'Leuven'),
		('Louvain-La-Neuve', 'Louvain-La-Neuve'),
		('Luik', 'Luik'),
		('Other', 'Other')
	)
	STATE_CHOICES = (
		('Antwerpen', 'Antwerpen'),
		('Brussel', 'Brussel'),
		('Henegouwen', 'Henegouwen'),
		('Namen', 'Namen'),
		('Oost-Vlaanderen', 'Oost-Vlaanderen'),
		('Luik', 'Luik'),
		('Luxemburg', 'Luxemburg'),
		('Vlaams-Brabant', 'Vlaams-Brabant'),
		('Waals-Brabant', 'Waals-Brabant'),
		('West-Vlaanderen', 'West-Vlaanderen'),
		('Other', 'Other')
	)
	COUNTRY_CHOICES = (
		('Austria', 'Austria'),
		('Belgium', 'Belgium'),
		('Croatia', 'Croatia'),
		('Czech Republic', 'Czech Republic'),
		('Denmark', 'Denmark'),
		('Estonia', 'Estonia'),
		('Finland', 'Finland'),
		('France', 'France'),
		('Germany', 'Germany'),
		('Greece', 'Greece'),
		('Hungary', 'Hungary'),
		('Italy', 'Italy'),
		('Latvia', 'Latvia'),
		('Lithuania', 'Lithuania'),
		('Norway', 'Norway'),
		('Poland', 'Poland'),
		('Portugal', 'Portugal'),
		('Romania', 'Romania'),
		('Slovakia', 'Slovakia'),
		('Slovenia', 'Slovenia'),
		('Spain', 'Spain'),
		('Sweden', 'Sweden'),
		('Switzerland', 'Switzerland'),
		('The Netherlands', 'The Netherlands'),
		('United Kingdom', 'United Kingdom')
	)
	id = models.AutoField(primary_key=True)
	time_created = models.DateTimeField(auto_now_add=True)
	time_modified = models.DateTimeField(auto_now=True, auto_now_add=True)
	lab_name = models.CharField(unique=True, max_length=128)
	lab_shortname = models.CharField(max_length=32, blank=True)
	lab_institutename = models.CharField(max_length=128, blank=True)
	lab_instituteshortname = models.CharField(max_length=32, blank=True)
	lab_departmentname = models.CharField(max_length=128, blank=True)
	lab_streetname = models.CharField(max_length=128, blank=True)
	lab_streetnumber = models.CharField(max_length=32, blank=True)
	lab_cityname = models.CharField(max_length=128, choices=CITY_CHOICES)
	lab_citycode = models.CharField(max_length=32)
	lab_statename = models.CharField(max_length=128, choices=STATE_CHOICES)
	lab_countryname = models.CharField(max_length=128, choices=COUNTRY_CHOICES)
	lab_addresspublic = models.BooleanField()
	lab_phone = models.CharField(max_length=32)
	lab_fax = models.CharField(max_length=32, blank=True)
	lab_email = models.CharField(max_length=32)
	lab_url = models.CharField(max_length=128)
	def __unicode__(self):
		return unicode(self.lab_name)
	class Meta:
		verbose_name = 'Laboratory'
		verbose_name_plural = 'Laboratories'
		ordering = ('lab_name',)
		db_table = u'laboratories'

class Personnel(models.Model):
	TITLE_CHOICES = (
		('Ms.', 'Ms.'),
		('Mrs.', 'Mrs.'),
		('Mr.', 'Mr.'),
		('Dr.', 'Dr.'),
		('Prof.', 'Prof.')
	)
	JOBTITLE_CHOICES = (
		('Administrator', 'Administrator'),
		('Nurse', 'Nurse'),
		('Lab Director', 'Lab Director'),
		('Scientific Director', 'Scientific Director'),
		('Medical Director', 'Medical Director'),
		('Staff', 'Staff'),
		('Other', 'Other')
	)
	DEGREE_CHOICES = (
		('BASc', 'BASc'),
		('BA', 'BA'),
		('MSc', 'MSc'),
		('Ph.D.', 'Ph.D.'),
		('M.D.', 'M.D.')
	)
	id = models.AutoField(primary_key=True)
	time_created = models.DateTimeField(auto_now_add=True)
	time_modified = models.DateTimeField(auto_now=True, auto_now_add=True)
	pers_lab = models.ForeignKey(Laboratory)
	pers_perspublic = models.BooleanField()
	pers_persdirector = models.BooleanField()
	pers_firstname = models.CharField(max_length=128)
	pers_lastname = models.CharField(max_length=128)
	pers_middlename = models.CharField(max_length=128, blank=True)
	pers_title = models.CharField(max_length=32, choices=TITLE_CHOICES, blank=True)
	pers_jobtitle = models.CharField(max_length=32, choices=JOBTITLE_CHOICES, blank=True)
	pers_degree = models.CharField(max_length=32, choices=DEGREE_CHOICES, blank=True)
	pers_phone = models.CharField(max_length=32)
	pers_fax = models.CharField(max_length=32, blank=True)
	pers_email = models.CharField(max_length=32)
	def __unicode__(self):
		return unicode("%s %s %s" % (self.pers_lastname, self.pers_firstname, self.pers_lab.lab_name))
	class Meta:
		verbose_name = 'Personnel'
		verbose_name_plural = 'Personnel'
		ordering = ('pers_lastname', 'pers_firstname',)
		db_table = u'personnel'

class Rizivcode(models.Model):
	id = models.AutoField(primary_key=True)
	time_created = models.DateTimeField(auto_now_add=True)
	time_modified = models.DateTimeField(auto_now=True, auto_now_add=True)
	riziv_code = models.CharField(unique=True, max_length=32)
	riziv_description = models.CharField(max_length=256)
	riziv_honorarium = models.CharField(max_length=128)
	riziv_ambulantreimbursement = models.CharField(max_length=128)
	riziv_hospitalizedreimbursement = models.CharField(max_length=128)
	def __unicode__(self):
		return unicode(self.riziv_code)
	class Meta:
		verbose_name = 'Riziv Code'
		verbose_name_plural = 'Riziv Codes'
		ordering = ('riziv_code',)
		db_table = u'rizivcode'
		
class Genetictest(models.Model):
	CATEGORY_CHOICES = (
		('Molecular Genetics', 'Molecular Genetics'),
		('Cytogenetics', 'Cytogenetics'),
		('Pathology', 'Pathology'),
		('Immunology', 'Immunology'),
		('Parasitology', 'Parasitology'),
		('Bacteriology', 'Bacteriology'),
		('Virology', 'Virology'),
		('Mycology', 'Mycology'),
		('Hematology', 'Hematology'),
		('Imaging', 'Imaging'),		
		('Culture', 'Culture')
	)
	CLINUTIL_CHOICES = (
		('Avoidance of invasive testing', 'Avoidance of invasive testing'),
		('Establish or confirm diagnosis', 'Establish or confirm diagnosis'),
		('Guidance for management', 'Guidance for management'),
		('Guidance for selecting a drug therapy and/or dose', 'Guidance for selecting a drug therapy and/or dose'),
		('Lifestyle planning', 'Lifestyle planning'),
		('Predicitive risk information for patient and/or family members', 'Predicitive risk information for patient and/or family members'),
		('Reproductive decision-making', 'Reproductive decision-making'),
		('Other', 'Other'),	
		('Sufficient research has not been conducted to demonstrate the utility of the test', 'Sufficient research has not been conducted to demonstrate the utility of the test')
	)
	LOCATION_CHOICES = (
		('Entire test performed in-house', 'Entire test performed in-house'),
		('Entire test performed at an outside laboratory', 'Entire test performed at an outside laboratory'),
		('Interpretation performed at an outside laboratory', 'Interpretation performed at an outside laboratory'),
		('Interpretation performed both in-house and at an outside laboratory', 'Interpretation performed both in-house and at an outside laboratory'),
		('Report generated at an outside laboratory', 'Report generated at an outside laboratory'),
		('Report generated both in-house and at an outside laboratory', 'Report generated both in-house and at an outside laboratory'),
		('Specimen preparation performed at an outside laboratory', 'Specimen preparation performed at an outside laboratory'),
		('Specimen preparation performed both in-house and at an outside laboratory', 'Specimen preparation performed both in-house and at an outside laboratory'),	
		('Wet lab work performed at an outside laboratory', 'Wet lab work performed at an outside laboratory'),
		('Wet lab work performed both in-house and at an outside laboratory', 'Wet lab work performed both in-house and at an outside laboratory')
	)
	TARGET_CHOICES = (
		('Whole genome sequencing', 'Whole genome sequencing'),
		('Whole exome sequencing', 'Whole exome sequencing'),
		('Gene panel sequencing', 'Gene panel sequencing'),
		('Gene sequencing', 'Gene sequencing'),
		('Exon sequencing', 'Exon sequencing'),
		('Chromosome rearrangements', 'Chromosome rearrangements'),
		('Copy number variations', 'Copy number variations')
	)
	id = models.AutoField(primary_key=True)
	time_created = models.DateTimeField(auto_now_add=True)
	time_modified = models.DateTimeField(auto_now=True, auto_now_add=True)
	test_lab = models.ForeignKey(Laboratory, related_name='testlab')
	test_location = models.CharField(max_length=128, choices=LOCATION_CHOICES)
	test_outsidelab = models.ForeignKey(Laboratory, related_name='outsidelab', null=True)
	test_loinc = models.CharField(max_length=128, blank=True)
	test_name = models.CharField(max_length=256)
	test_shortname = models.CharField(max_length=32, blank=True)
	test_commercialname = models.CharField(max_length=256, blank=True)
	test_personnelcontact = models.ForeignKey(Personnel)
	test_url = models.CharField(max_length=128, blank=True)
	test_category = models.CharField(max_length=128, choices=CATEGORY_CHOICES)
	test_target = models.CharField(max_length=128, choices=TARGET_CHOICES)
	test_tat = models.CharField(max_length=128, blank=True)
	test_cost = models.CharField(max_length=128, blank=True)
	test_rizivcode = models.ForeignKey(Rizivcode)
	test_analyticalsensitivity = models.CharField(max_length=128, blank=True)
	test_analyticalspecificity = models.CharField(max_length=128, blank=True)
	test_analyticalprecision = models.CharField(max_length=128, blank=True)
	test_clinicalvalidity = models.CharField(max_length=128, blank=True)
	test_clinicalutility = models.CharField(max_length=128, choices=CLINUTIL_CHOICES, blank=True)
#	test_order = models.ForeignKey(Order)
	def __unicode__(self):
		return unicode("%s %s" % (self.test_name, self.test_lab.lab_name))
	class Meta:
		verbose_name = 'Genetic test'
		verbose_name_plural = 'Genetic tests'
		ordering = ('test_name',)
		db_table = u'genetictests'
		
class Disease(models.Model):
	id = models.AutoField(primary_key=True)
	time_created = models.DateTimeField(auto_now_add=True)
	time_modified = models.DateTimeField(auto_now=True, auto_now_add=True)
	disease_name = models.CharField(unique=True, max_length=128)
	disease_shortname = models.CharField(max_length=32)
	disease_synonym = models.CharField(max_length=128)

templates/getregi/detail_disease.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Disease - {{ disease.disease_name }}</title>
	<meta name="author" content="Kim Van Roey" />
	<meta name="date" content="21/08/2015" />
	<meta name="language" content="english" />
	<meta name="charset" content="utf-8" />
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js""></script>
	<noscript>Sorry, your browser does not support JavaScript!</noscript>

	<link rel="stylesheet" type="text/css" href="{% static 'getregi/gtdb_style.css' %}" />
	
</head>

<body>
	
	<div class="headerBox">
		<img class="titleImg" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="75" height="60" border="1px solid #FFFFFF" />
		<a class="navigationBar" id="Personnel" href="/personnel/" >Personnel</a>
		<a class="navigationBar" id="Laboratories" href="/laboratories/" >Laboratories</a>
		<a class="navigationBar" id="Methodology" href="/methodology/" >Methodology</a>
		<a class="navigationBar" id="Genetictests" href="/genetictests/" >Genetic tests</a>
		<a class="navigationBar" id="Genes" href="/genes/" >Genes</a>
		<a class="navigationBar" id="Diseases" href="/diseases/" >Diseases</a>
		<a class="navigationBar" id="Browse" href="/browse/" >Browse</a>
		<a class="navigationBar" id="Search" href="/search/" >Search</a>
		<a class="navigationBar" id="Home" href="/gtdb/" >Home</a>
	</div>

	<div class='middleBox'>
		<h1>{{ disease.disease_name|capfirst }}</h1>
		
		<div class="subTitleBox">Disease details</div>
		<ul>
			<li><p><i>Name:</i> {{ disease.disease_name|capfirst }} ({{ disease.disease_shortname|capfirst }})</p></li>
			<li><p><i>Synonyms:</i> {{ disease.disease_synonym|capfirst }}</p></li>
			<li><p><i>Description:</i> {{ disease.disease_description|capfirst }}</p></li>
			<li><p><i>Cross references:</i></p></li>
				<ul>
				{% if disease.disease_xrefomim %} 
				<li><p><a href="http://www.omim.org/entry/{{ disease.disease_xrefomim }}" target="blank">OMIM entry #{{ disease.disease_xrefomim }}</a></p></li> 
				{% endif %}
				{% if disease.disease_xreforphanet %}
				<li><p><a href="http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=EN&Expert={{ disease.disease_xreforphanet }}" target="blank">Orphanet entry ORPHA{{ disease.disease_xreforphanet }}</a></p></li> 
				{% endif %}
				{% if disease.disease_xref %}
				<li><p><a>{{ disease.disease_xref }}</a></p></li>
				{% endif %}
				</ul>
			</li>
		</ul>
		
		<div class="subTitleBox">Associated genes</div>
			{% if disease.diseasegene_set.all %}
			{% for a in disease.diseasegene_set.all %}
			<ul>
				<li><p><a href="/genes/{{ a.gene.id }}/" target="blank">{{ a.gene.gene_name|capfirst }} ({{ a.gene.gene_shortname|capfirst }})</a></p></li>
			</ul>
			{% endfor %}
			{% else %}
			<ul>
				<li><p><i>No genes associated with this disease</i></p></li>
			</ul>
			{% endif %}
		
		<div class="subTitleBox">Genetic tests</div>
			{% if disease.testdisease_set.all %}
			{% for a in disease.testdisease_set.all %}
			<ul>
				<li><p><a href="/genetictests/{{ a.test.id }}/" target="blank">{{ a.test.test_name|capfirst }} ({{ a.test.test_lab.lab_name|capfirst }})</a></p></li>
			</ul>
			{% endfor %}
			{% else %}
			<ul>
				<li><p><i>No genetic tests associated with this disease</i></p></li>
			</ul>
			{% endif %}
			<br/>
		
	</div>

	<div class="footerBox">
		<p class="footerText">IN COLLABORATION WITH</p>
		<div class="titleBox">
		<a class="img" href="http://www.wiv-isp.be/Pages/NL-Home.aspx" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.riziv.fgov.be/nl/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/riziv.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.inami.fgov.be/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/inami.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.health.belgium.be/eportal/index.htm" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/fod.png' %}" width="42" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.orpha.net" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/orphanet.png' %}" width="188" height="40" border="1px solid #FFFFFF" />
		</a>
		</div>
	</div>
	
</body>
</html>

templates/getregi/detail_laboratory.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>Laboratory - {{ laboratory.lab_name }}</title>
	<meta name="author" content="Kim Van Roey" />
	<meta name="date" content="21/08/2015" />
	<meta name="language" content="english" />
	<meta name="charset" content="utf-8" />
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js""></script>
	<noscript>Sorry, your browser does not support JavaScript!</noscript>

	<link rel="stylesheet" type="text/css" href="{% static 'getregi/gtdb_style.css' %}" />
	
</head>

<body>
	
	<div class="headerBox">
		<img class="titleImg" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="75" height="60" border="1px solid #FFFFFF" />
		<a class="navigationBar" id="Personnel" href="/personnel/" >Personnel</a>
		<a class="navigationBar" id="Laboratories" href="/laboratories/" >Laboratories</a>
		<a class="navigationBar" id="Methodology" href="/methodology/" >Methodology</a>
		<a class="navigationBar" id="Genetictests" href="/genetictests/" >Genetic tests</a>
		<a class="navigationBar" id="Genes" href="/genes/" >Genes</a>
		<a class="navigationBar" id="Diseases" href="/diseases/" >Diseases</a>
		<a class="navigationBar" id="Browse" href="/browse/" >Browse</a>
		<a class="navigationBar" id="Search" href="/search/" >Search</a>
		<a class="navigationBar" id="Home" href="/gtdb/" >Home</a>
	</div>

	<div class='middleBox'>
		<h1>{{ laboratory.lab_name|capfirst }}</h1>
		
		<div class="subTitleBox">Contact</div>
		<ul><li>
			<p><b>Address:</b></p>
			<p>{{ laboratory.lab_name|capfirst }}</p>
			<p>{{ laboratory.lab_departmentname|capfirst }}</p>
			<p>{{ laboratory.lab_institutename|capfirst }}</p>
			<p>{{ laboratory.lab_streetname|capfirst }} {{ laboratory.lab_streetnumber }}</p>
			<p>{{ laboratory.lab_citycode }} {{ laboratory.lab_cityname|capfirst }}</p>
			<p>{{ laboratory.lab_statename }}, {{ laboratory.lab_countryname }}</p>
		</li></ul>
		
		<ul><li>
			<p><b>Contact:</b></p>
			<p><i>Phone:</i> {{ laboratory.lab_phone }}</p>
			<p><i>Fax:</i> {{ laboratory.lab_fax }}</p>
			<p><i>E-mail:</i> {{ laboratory.lab_email }}</p>
			<p><i>Website:</i> <a href="{{ laboratory.lab_url }}" target="blank">{{ laboratory.lab_url }}</a></p>
		</li></ul>
		
		{% if laboratory.testlab.all %}
		<div class="subTitleBox">Genetic tests</div>
			{% for a in laboratory.testlab.all %}
			<ul>
				<li>
					<p><a href="/genetictests/{{ a.id }}/">{{ a.test_name|capfirst }}</a></p>
				</li>
			</ul>
			{% endfor %}
		{% else %}
		{% endif %}
<!--		
		{% if laboratory.outsidelab.all %}
		<div class="subTitleBox">Genetic tests</div>
			{% for a in laboratory.outsidelab.all %}
			<ul>
				<li>
					<p><a href="/genetictests/{{ a.id }}/">{{ a.test_name|capfirst }}</a></p>
				</li>
			</ul>
			{% endfor %}
		{% else %}
		{% endif %}
-->		
		{% if laboratory.personnel_set.all %}
		<div class="subTitleBox">Personnel</div>
			{% for a in laboratory.personnel_set.all %}
			<ul>
				<li>
					<p><a href="/personnel/{{ a.id }}/">{{ a.pers_title }} {{ a.pers_lastname|capfirst }}, {{ a.pers_firstname|capfirst }} {{ a.pers_middlename|capfirst }} ({{ a.pers_degree }}) - {{ a.pers_jobtitle }}</a></p>
					<p><i>Phone:</i> {{ a.pers_phone }}</p>
					<p><i>Fax:</i> {{ a.pers_fax }}</p>
					<p><i>E-mail:</i> {{ a.pers_email }}</p>
				</li>
			</ul>
			{% endfor %}
		{% else %}
		{% endif %}
		
		<br/>
	</div>
	
	<div class="footerBox">
		<p class="footerText">IN COLLABORATION WITH</p>
		<div class="titleBox">
		<a class="img" href="http://www.wiv-isp.be/Pages/NL-Home.aspx" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.riziv.fgov.be/nl/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/riziv.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.inami.fgov.be/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/inami.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.health.belgium.be/eportal/index.htm" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/fod.png' %}" width="42" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.orpha.net" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/orphanet.png' %}" width="188" height="40" border="1px solid #FFFFFF" />
		</a>
		</div>
	</div>
	
</body>
</html>

templates/getregi/index_browse.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
	<title>GTDB - Browse</title>
	<meta name="author" content="Kim Van Roey" />
	<meta name="date" content="21/08/2015" />
	<meta name="language" content="english" />
	<meta name="charset" content="utf-8" />
	
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js""></script>
	<noscript>Sorry, your browser does not support JavaScript!</noscript>

	<link rel="stylesheet" type="text/css" href="{% static 'getregi/gtdb_style.css' %}" />
	
</head>

<body>
	
	<div class="headerBox">
		<img class="titleImg" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="75" height="60" border="1px solid #FFFFFF" />
		<a class="navigationBar" id="Personnel" href="/personnel/" >Personnel</a>
		<a class="navigationBar" id="Laboratories" href="/laboratories/" >Laboratories</a>
		<a class="navigationBar" id="Methodology" href="/methodology/" >Methodology</a>
		<a class="navigationBar" id="Genetictests" href="/genetictests/" >Genetic tests</a>
		<a class="navigationBar" id="Genes" href="/genes/" >Genes</a>
		<a class="navigationBar" id="Diseases" href="/diseases/" >Diseases</a>
		<a class="navigationBar" id="current" href="/browse/" >Browse</a>
		<a class="navigationBar" id="Search" href="/search/" >Search</a>
		<a class="navigationBar" id="Home" href="/gtdb/" >Home</a>
	</div>

	<div class='middleBox'>
		<div class="subTitleBox">Browse GTDB</div>
		<div class='browseBox'>
		<p class="input">Browse GTDB by:
		<a class="browseButton" id="Disease" href="/diseases/" >Disease</a>
		<a class="browseButton" id="Gene" href="/genes/" >Gene</a>
		<a class="browseButton" id="Genetictests" href="/genetictests/" >Genetic test</a>
		<a class="browseButton" id="Methodology" href="/methodology/" >Methodology</a>
		<a class="browseButton" id="Laboratories" href="/laboratories/" >Laboratory</a>
		<a class="browseButton" id="Personnel" href="/personnel/" >Personnel</a>
		</p>
		</div>
	</div>
	
	<div class="footerBox">
		<p class="footerText">IN COLLABORATION WITH</p>
		<div class="titleBox">
		<a class="img" href="http://www.wiv-isp.be/Pages/NL-Home.aspx" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/wiv-isp_2.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.riziv.fgov.be/nl/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/riziv.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.inami.fgov.be/" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/inami.png' %}" width="51" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.health.belgium.be/eportal/index.htm" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/fod.png' %}" width="42" height="40" border="1px solid #FFFFFF" />
		</a>
		<a class="img" href="http://www.orpha.net" target="blank">
		<img class="palign_img" src="{% static 'getregi/images/orphanet.png' %}" width="188" height="40" border="1px solid #FFFFFF" />
		</a>
		</div>
	</div>
	
</body>
</html>